source/index.html.md
=> Add java sdk docs

source/index.html.md
=> Fix a typo in CreateTransaction curl command

source/index.html.md
API Doc for the Ruby sdk, which is provided here https://github.com/FireStack-Lab/LaksaRuby
- [*] **ready for review**
=> api doc for ruby

source/index.html.md
Add ruby methods and fix js methods.
=> Minor edits to methods

README.md, source/index.html.md
* Added response details for the GetTransactionsForTxBlock
* Added style changes using `prettier`
=> docs: Response details for GetTransactionsForTxBlock

source/index.html.md
add api docs for Python @evesnow91 
Python code snippets using pyzil
=> APIDoc for Python

source/index.html.md
=> Minor formatting changes

source/index.html.md
Update json output for `GetLatestTxBlock` and `GetTxBlock`
=> Add blockhash for TxBlk

source/index.html.md
=> Add changes for v5.0

source/index.html.md
Add GetTotalCoinSupply documentation. May need some help on SDK side.
=> Add GetTotalCoinSupply

source/index.html.md
=> Update a few SDKs

README.md, source/index.html.md
=> Add docs of gozilliqa-sdk

source/index.html.md
Add documentation for api GetPendingTxn, covered curl,js,golang and java
=> Add GetPendingTxn doc

source/index.html.md
Add description for GetPendingTxn.
=> chore: add description for pendingtx

source/index.html.md
Since we have a rich content inside transaction receipt, we can update the example response for `GetTransaction`.
=> chore: update example reponse of getting transaction

.travis.yml, Gemfile.lock
=> chore: update gemfile.lock

CODE_OF_CONDUCT.md
Update Gitter link to Maintainer email
=> Update Gitter link to Maintainer email

source/index.html.md
=> Add table of possible results for GetPendingTxn

source/index.html.md
Add description for `GetPendingTxns` and `GetTxnBodiesForTxBlock`
=> Add API docs for GetPendingTxns and GetTxnBodiesForTxBlock

source/index.html.md
This PR is to add more examples for field `exceptions` and `accepted` in transaction receipt.
=> chore: add example for exception and accepted

source/index.html.md
=> fix Python example of API DSBlockListing

source/index.html.md
Moved `GetPendingTxns` immediately after `GetPendingTxn`
Moved `GetTxnBodiesForTxBlock` immediately after `GetTransactionsForTxBlock`
Fixed some typos
=> Reorganized API

source/index.html.md
Add a note to `GetTxnBodiesForTxBlock` to highlight that this API will not be accessible of the public API service
=> Add a note to GetTxnBodiesForTxBlock

source/index.html.md
=> Added GetMinerInfo

source/index.html.md
=> fix: docs examples

source/index.html.md
=> fix: failed txn example

source/index.html.md
=> Updated GetPendingTxn(s) for version 6.3.0

source/index.html.md
Add back older API information for `getpendingtxn` and `getpendingtxns`
=> Add back older api information

source/index.html.md
Remove the note for `GetTxnBodiesForTxBlock`.
=> chore: delete note for gettransactionsfortxblock

source/index.html.md
Update the pending/dropped codes for v700
=> Modify codes
